### PR TITLE
Dynamic area

### PR DESCRIPTION
**Pull request by juliephiloche**
Hi Stefan,

I've improved your funnel chart for internal needs.
Could you check if you agree and merge with you master ?

Thanks.
Julie

### CODE REVIEW

**Comment by stefanwalther** [comment]
Sure, will review, thx.

**Comment by juliephiloche** [comment]
Hi Stefan,

I'm looking to use basic colors and persistent colors in your chart. I
found "colorSchemes" object in this json file :
http://localhost:4848/resources/themes/highvis/theme.json

Do you know how to easily use it ? Does it exists a lib/api or I have to
load the json and directly work with ? The same for the permanent color,
have you an advice ?

Thanks,
Julie

2015-11-13 22:20 GMT+01:00 Stefan Walther notifications@github.com:

**Comment by juliephiloche** [comment]
Hi Stefan,

Not yet looking at my changes ? Is there a problem ?
I've added the use of colorSchemes and persistent colors.

Thanks,
Julie

2015-11-16 10:51 GMT+01:00 Julie Philoche julie.philoche.dev@gmail.com:

**Comment by juliephiloche** [comment]
Hi Stefan,

I come back to you for my merges. 
Did you forgot me or simply haven't time to check ? 

Thank you to keep me in touch.
Julie

**Comment by stefanwalther** [comment]
Hi @juliephiloche, while I like your changes, I see a problem with it: You are using an internal module (`core.utils.theme`) which is not exposed, therefore not supported. In general I do not want to expose unsupported stuff in my visualizations. But please feel free to continue to work on your fork.

But what we can maybe do is to use the now in Qlik Sense 2.2 supported colorpicker? What do you think?

Sorry for not having better news.

Regards
Stefan

**Comment by juliephiloche** [comment]
Hi Stefan,

Thank you for your return. I agree with about the changes we can do with
2.2. Unfortunately, I changed of job in February (now C#.net dev) and I'm
not sure to have time to do it. I copy this mail to an ex-colleague who
probably has more time then me.

Regards,
Julie

**Comment by stefanwalther** [comment]
OK, thx. Good luck in your new role!

**Pull request closed without merging**
